FROM eclipse-temurin:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Package the application (skip tests to make the process faster)
RUN ./mvnw clean package -DskipTests

# Run the application
CMD ["java", "-jar", "target/ProductSpringBoot-0.0.1-SNAPSHOT.jar"]
